name: AlchemyRedirected
version: '${version}'
main: dev.alchemyredirected.AlchemyRedirected
api-version: '1.21'
author: rutaji
description: Throw ingredients into cauldron to craft potions with multiple effects.
depend: [PlaceholderAPI]
softdepend: [MMOCore,AuraSkills]
commands:
  Ingredients:
    description: Shows gui with all ingredients
    usage: /Ingredients
  alchemyredirected:
    description: Alchemy Redirected admin commands
    usage: /alchemyredirected reload
    permission: alchemyredirected.reload
permissions:
  alchemyredirected.reload:
    description: Allows reloading ingredients.yml
    default: op